import { createContext, useContext, useState, useEffect, type ReactNode } from 'react';

type Lang = 'en' | 'ar';

const translations: Record<Lang, Record<string, string>> = {
  en: {
    dashboard: 'Dashboard',
    users: 'Users',
    tribes: 'Tribes',
    sessions: 'Sessions',
    quizzes: 'Quizzes',
    xpLeaderboard: 'XP & Leaderboard',
    bonusQr: 'Bonus',
    sports: 'Sports',
    logout: 'Logout',
    adminPanel: 'Admin Panel',
    createUser: 'Create User',
    removeAttendees: 'Remove Attendees',
    allRoles: 'All Roles',
    attendee: 'Attendee',
    staff: 'Staff',
    admin: 'Admin',
    superAdmin: 'Super Admin',
    name: 'Name',
    email: 'Email',
    role: 'Role',
    tribe: 'Tribe',
    xp: 'XP',
    actions: 'Actions',
    loading: 'Loading...',
    noUsersFound: 'No users found',
    noTribe: 'No Tribe',
    createTribe: 'Create Tribe',
    tribeName: 'Tribe Name',
    description: 'Description',
    color: 'Color',
    maxMembers: 'Max Members',
    members: 'Members',
    totalXp: 'Total XP',
    capacity: 'Capacity',
    save: 'Save Changes',
    cancel: 'Cancel',
    close: 'Close',
    create: 'Create',
    newSession: 'New Session',
    attendance: 'Attendance',
    attendees: 'Attendees',
    individual: 'Individual',
    awardXp: 'Award XP',
    xpHistory: 'XP History',
    amount: 'Amount',
    reason: 'Reason',
    generateQr: 'Generate QR',
    staffAward: 'Staff Award',
    teams: 'Teams',
    matches: 'Matches',
    standings: 'Standings',
    addPlayer: 'Add Player',
    removePlayer: 'Remove Player',
    createTeam: 'Create Team',
    scheduleMatch: 'Schedule Match',
    totalUsers: 'Total Users',
    activeSessions: 'Active Sessions',
    totalAttendance: 'Total Attendance',
    totalXpAwarded: 'Total XP Awarded',
    activeQuizzes: 'Active Quizzes',
    viewDetails: 'View Details',
    adjustXp: 'Adjust XP (Add / Deduct)',
    qrToken: 'QR Token',
    lastLogin: 'Last Login',
    joined: 'Joined',
    church: 'Church',
    diocese: 'Diocese',
    phone: 'Phone',
    status: 'Status',
    level: 'Level',
    password: 'Password',
    unlimited: 'Unlimited',
    selected: 'selected',
    searchAttendees: 'Search attendees...',
    position: 'Position',
    language: 'Language',
    levels: 'Levels',
    addLevel: 'Add Level',
    recalculate: 'Recalculate',
    levelsDescription: 'Levels are auto-assigned to users based on their XP thresholds.',
    editSession: 'Edit Session',
    sessionTitle: 'Session Title',
    speaker: 'Speaker',
    location: 'Location',
    date: 'Date',
    startTime: 'Start',
    endTime: 'End',
    xpReward: 'XP Reward',
    maxCapacity: 'Max Capacity',
    copyToken: 'Copy Token',
    regenerateQr: 'Regenerate QR',
    info: 'Info',
    edit: 'Edit',
    avgScore: 'Avg Score',
    conferenceXp: 'Conference XP',
    sportsXp: 'Sports XP',
    winXp: 'Win XP',
    drawXp: 'Draw XP',
    lossXp: 'Loss XP',
    // Bonus
    bonusCreated: 'Bonus QR created!',
    deactivated: 'QR deactivated',
    xpAwarded: 'Bonus XP awarded!',
    viewClaims: 'View Claims',
    deactivate: 'Deactivate',
    claims: 'Claims',
    active: 'Active',
    inactive: 'Inactive',
    noBonusYet: 'No bonus QR codes yet',
    noClaimsYet: 'No claims yet',
    xpAmount: 'XP Amount',
    label: 'Label',
    maxClaims: 'Max Claims',
    generate: 'Generate',
    bonusLabelPlaceholder: 'e.g. Workshop bonus',
    staffAwardDesc: 'Award bonus XP directly to a user by scanning their personal QR code.',
    userQrToken: 'User QR Token (UUID)',
    pasteUserQr: 'Paste user QR token',
    reasonPlaceholder: 'e.g. Great participation',
    // Quizzes
    noQuizzesYet: 'No quizzes yet',
    questions: 'Questions',
    pass: 'Pass',
    submissions: 'Submissions',
    createQuiz: 'Create Quiz',
    quizTitle: 'Quiz Title',
    passPercentage: 'Pass %',
    timeLimitSeconds: 'Time (s)',
    addQuestion: 'Add Question',
    noQuestionsYet: 'No questions yet. Click + to add.',
    multipleChoice: 'Multiple Choice',
    trueFalse: 'True/False',
    shortAnswer: 'Short Answer',
    options: 'Options',
    option: 'Option',
    correctAnswer: 'Correct Answer',
    explanation: 'Explanation',
    whyThisAnswer: 'Why this answer',
    points: 'Points',
    order: 'Order',
    activate: 'Activate',
    complete: 'Complete',
    qrCode: 'QR Code',
    copiedToClipboard: 'Copied!',
    // Sessions
    noSessionsYet: 'No sessions yet',
    noOneAttendedYet: 'No one has attended yet',
    // Sports
    noPlayersYet: 'No players yet',
    notApplicable: 'N/A',
    confirmRemovePlayer: 'Remove player from team?',
    noMatchesScheduled: 'No matches scheduled',
    vs: 'vs',
    score: 'Score',
    homeScore: 'Home score',
    awayScore: 'Away score',
    teamName: 'Team Name',
    maxRoster: 'Max Roster',
    selectTeam: 'Select...',
    selectUser: 'Select User',
    searchUsers: 'Search users by name or email...',
    noResults: 'No results found',
    dateTime: 'Date & Time',
    schedule: 'Schedule',
    // XP/Levels
    activeParticipation: 'e.g. Active participation',
    levelNamePlaceholder: 'Level Name (e.g. Bronze, Silver, Gold)',
    noLevelsYet: 'No levels defined. Create levels to reward users.',
    confirmDeleteLevel: 'Delete level?',
    chooseUser: 'Choose user...',
    award: 'Award',
    // Users
    confirmDeleteAttendees: 'This will soft-delete ALL attendee accounts. Are you sure?',
    noSessionsAttended: 'No sessions attended',
    noQuizzesTaken: 'No quizzes taken',
    passed: 'Passed',
    failed: 'Failed',
    noBonusClaimed: 'No bonus claimed',
    publications: 'Publications',
  },
  ar: {
    dashboard: 'لوحة التحكم',
    users: 'المستخدمين',
    tribes: 'الفرق',
    sessions: 'المجموعات',
    quizzes: 'المسابقات',
    xpLeaderboard: 'النقاط والترتيب',
    bonusQr: 'المكافآت',
    sports: 'الرياضة',
    logout: 'تسجيل خروج',
    adminPanel: 'لوحة الإدارة',
    createUser: 'إنشاء مستخدم',
    removeAttendees: 'حذف الحضور',
    allRoles: 'جميع الأدوار',
    attendee: 'مشترك',
    staff: 'مشرف',
    admin: 'مسؤول',
    superAdmin: 'مسؤول أعلى',
    name: 'الاسم',
    email: 'البريد',
    role: 'الدور',
    tribe: 'المجموعة',
    xp: 'النقاط',
    actions: 'إجراءات',
    loading: 'جاري التحميل...',
    noUsersFound: 'لا يوجد مستخدمين',
    noTribe: 'بدون مجموعة',
    createTribe: 'إنشاء مجموعة',
    tribeName: 'اسم المجموعة',
    description: 'الوصف',
    color: 'اللون',
    maxMembers: 'أقصى عدد أعضاء',
    members: 'الأعضاء',
    totalXp: 'إجمالي النقاط',
    capacity: 'السعة',
    save: 'حفظ التعديلات',
    cancel: 'إلغاء',
    close: 'إغلاق',
    create: 'إنشاء',
    newSession: 'جلسة جديدة',
    attendance: 'الحضور',
    attendees: 'المشتركين',
    individual: 'فردي',
    awardXp: 'منح نقاط',
    xpHistory: 'سجل النقاط',
    amount: 'المبلغ',
    reason: 'السبب',
    generateQr: 'إنشاء QR',
    staffAward: 'منحة مباشرة',
    teams: 'الفرق',
    matches: 'المباريات',
    standings: 'الترتيب',
    addPlayer: 'إضافة لاعب',
    removePlayer: 'إزالة لاعب',
    createTeam: 'إنشاء فريق',
    scheduleMatch: 'جدولة مباراة',
    totalUsers: 'إجمالي المستخدمين',
    activeSessions: 'المجموعات النشطة',
    totalAttendance: 'إجمالي الحضور',
    totalXpAwarded: 'إجمالي النقاط الممنوحة',
    activeQuizzes: 'المسابقات النشطة',
    viewDetails: 'عرض التفاصيل',
    adjustXp: 'تعديل النقاط (إضافة / خصم)',
    qrToken: 'رمز QR',
    lastLogin: 'آخر دخول',
    publications: 'المنشورات',
    joined: 'تاريخ التسجيل',
    church: 'الكنيسة',
    diocese: 'الإيبارشية',
    phone: 'الهاتف',
    status: 'الحالة',
    level: 'المستوى',
    password: 'كلمة المرور',
    unlimited: 'غير محدود',
    selected: 'محدد',
    searchAttendees: 'بحث عن الحضور...',
    position: 'المركز',
    language: 'اللغة',
    levels: 'المستويات',
    addLevel: 'إضافة مستوى',
    recalculate: 'إعادة حساب',
    levelsDescription: 'يتم تعيين المستويات تلقائياً بناءً على نقاط XP.',
    editSession: 'تعديل الجلسة',
    sessionTitle: 'عنوان الجلسة',
    speaker: 'المتحدث',
    location: 'المكان',
    date: 'التاريخ',
    startTime: 'البداية',
    endTime: 'النهاية',
    xpReward: 'نقاط المكافأة',
    maxCapacity: 'الحد الأقصى',
    copyToken: 'نسخ الرمز',
    regenerateQr: 'تجديد QR',
    info: 'المعلومات',
    edit: 'تعديل',
    avgScore: 'متوسط الدرجة',
    conferenceXp: 'نقاط المؤتمر',
    sportsXp: 'نقاط الرياضة',
    winXp: 'نقاط الفوز',
    drawXp: 'نقاط التعادل',
    lossXp: 'نقاط الخسارة',
    // Bonus
    bonusCreated: 'تم إنشاء QR المكافأة!',
    deactivated: 'تم تعطيل QR',
    xpAwarded: 'تم منح النقاط!',
    viewClaims: 'عرض المطالبات',
    deactivate: 'تعطيل',
    claims: 'المطالبات',
    active: 'نشط',
    inactive: 'غير نشط',
    noBonusYet: 'لا توجد رموز مكافآت بعد',
    noClaimsYet: 'لا توجد مطالبات بعد',
    xpAmount: 'مقدار النقاط',
    label: 'التسمية',
    maxClaims: 'الحد الأقصى للمطالبات',
    generate: 'إنشاء',
    bonusLabelPlaceholder: 'مثال: مكافأة ورشة العمل',
    staffAwardDesc: 'منح نقاط مباشرة للمستخدم عبر مسح رمز QR الخاص به.',
    userQrToken: 'رمز QR المستخدم (UUID)',
    pasteUserQr: 'الصق رمز QR المستخدم',
    reasonPlaceholder: 'مثال: مشاركة ممتازة',
    // Quizzes
    noQuizzesYet: 'لا توجد مسابقات بعد',
    questions: 'الأسئلة',
    pass: 'النجاح',
    submissions: 'المشاركات',
    createQuiz: 'إنشاء مسابقة',
    quizTitle: 'عنوان المسابقة',
    passPercentage: 'نسبة النجاح %',
    timeLimitSeconds: 'الوقت (ث)',
    addQuestion: 'إضافة سؤال',
    noQuestionsYet: 'لا توجد أسئلة بعد. اضغط + للإضافة.',
    multipleChoice: 'اختيار من متعدد',
    trueFalse: 'صح / خطأ',
    shortAnswer: 'إجابة قصيرة',
    options: 'الخيارات',
    option: 'خيار',
    correctAnswer: 'الإجابة الصحيحة',
    explanation: 'التوضيح',
    whyThisAnswer: 'لماذا هذه الإجابة',
    points: 'النقاط',
    order: 'الترتيب',
    activate: 'تفعيل',
    complete: 'إكمال',
    qrCode: 'رمز QR',
    copiedToClipboard: 'تم النسخ!',
    // Sessions
    noSessionsYet: 'لا توجد مجموعات بعد',
    noOneAttendedYet: 'لم يحضر أحد بعد',
    // Sports
    noPlayersYet: 'لا يوجد لاعبين بعد',
    notApplicable: 'غ/م',
    confirmRemovePlayer: 'إزالة اللاعب من الفريق؟',
    noMatchesScheduled: 'لا توجد مباريات مجدولة',
    vs: 'ضد',
    score: 'النتيجة',
    homeScore: 'نتيجة المضيف',
    awayScore: 'نتيجة الضيف',
    teamName: 'اسم الفريق',
    maxRoster: 'الحد الأقصى للقائمة',
    selectTeam: 'اختر...',
    selectUser: 'اختر مستخدم',
    searchUsers: 'ابحث بالاسم أو البريد...',
    noResults: 'لا توجد نتائج',
    dateTime: 'التاريخ والوقت',
    schedule: 'جدولة',
    // XP/Levels
    activeParticipation: 'مثال: مشاركة فعالة',
    levelNamePlaceholder: 'اسم المستوى (مثال: برونزي، فضي، ذهبي)',
    noLevelsYet: 'لا توجد مستويات. أنشئ مستويات لمكافأة المستخدمين.',
    confirmDeleteLevel: 'حذف المستوى؟',
    chooseUser: 'اختر مستخدم...',
    award: 'منح',
    // Users
    confirmDeleteAttendees: 'سيتم حذف جميع حسابات المشتركين. هل أنت متأكد؟',
    noSessionsAttended: 'لم يحضر مجموعات',
    noQuizzesTaken: 'لم يشارك في مسابقات',
    passed: 'ناجح',
    failed: 'راسب',
    noBonusClaimed: 'لا توجد مكافآت',
  },
};

interface LangContextType {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: (key: string) => string;
  dir: 'ltr' | 'rtl';
}

const LangContext = createContext<LangContextType>({
  lang: 'en',
  setLang: () => {},
  t: (key) => key,
  dir: 'ltr',
});

export function LangProvider({ children }: { children: ReactNode }) {
  const [lang, setLang] = useState<Lang>(() => {
    const saved = (localStorage.getItem('admin-lang') as Lang) || 'ar';
    // Apply immediately to avoid flash
    document.documentElement.dir = saved === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = saved;
    return saved;
  });

  useEffect(() => {
    localStorage.setItem('admin-lang', lang);
    document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = lang;
  }, [lang]);

  const t = (key: string) => translations[lang][key] || key;
  const dir = lang === 'ar' ? 'rtl' : 'ltr';

  return (
    <LangContext.Provider value={{ lang, setLang, t, dir }}>
      {children}
    </LangContext.Provider>
  );
}

export function useLang() {
  return useContext(LangContext);
}
